[package]
authors = ['GalacticCouncil']
edition = '2018'
name = 'primitives'
version = '3.0.0'

[build-dependencies]
wasm-builder-runner = {package = 'substrate-wasm-builder-runner', version = '1.0.5'}

[dependencies]
primitive-types = {default-features = false, version = '0.7.2'}
serde = {features = ['derive'], optional = true, version = '1.0.101'}
codec = {package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Substrate dependencies

frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}

[dev-dependencies]
sp-core = {default-features = false, version = '3.0.0'}
sp-io = {default-features = false, version = '3.0.0'}


[features]
default = ['std']
std = [
  'codec/std',
  'primitive-types/std',
  'serde',
  'frame-support/std',
  'sp-std/std',
]
