[package]
name = "basilisk-runtime"
version = "125.0.0"
authors = ["GalacticCouncil"]
edition = "2021"
homepage = "https://github.com/galacticcouncil/Basilisk-node"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/Basilisk-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[dependencies]
hex-literal = { workspace = true }
serde = { workspace = true, optional = true }
codec = {  workspace = true }
scale-info = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }

# local dependencies
primitives = { default-features = false, path = "../../primitives" }
pallet-marketplace = { workspace = true, default-features = false }
pallet-xyk-liquidity-mining = { workspace = true , default-features = false }
pallet-xyk-liquidity-mining-benchmarking = { workspace = true, optional = true, default-features = false }

pallet-treasury = { workspace = true }
pallet-democracy = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-elections-phragmen = { workspace = true }
pallet-tips = { workspace = true }
pallet-identity = { workspace = true }
pallet-state-trie-migration = { workspace = true }

# HydraDX dependencies
hydradx-traits = { workspace = true }
hydra-dx-math = { workspace = true }
pallet-transaction-multi-payment = { workspace = true }
pallet-relaychain-info = { workspace = true }
pallet-asset-registry = { workspace = true }
hydradx-adapters = { workspace = true }
pallet-nft = { workspace = true }
pallet-currencies = { workspace = true }
pallet-transaction-pause = { workspace = true }
pallet-route-executor = { workspace = true }
warehouse-liquidity-mining = { workspace = true }
pallet-ema-oracle = { workspace = true }
pallet-duster = { workspace = true }
pallet-collator-rewards = { workspace = true }
pallet-xyk = { workspace = true }
pallet-lbp = { workspace = true }
pallet-broadcast = { workspace = true }
pallet-staking = { workspace = true }

# collator support
pallet-collator-selection = { workspace = true }
pallet-authorship = { workspace = true }

# ORML dependencies
orml-tokens = { workspace = true }
orml-traits = { workspace = true }
orml-vesting = { workspace = true }
orml-benchmarking = { workspace = true, optional = true }

# orml XCM support
orml-xtokens = { workspace = true }
orml-xcm-support = { workspace = true }
orml-unknown-tokens = { workspace = true }
orml-xcm = { workspace = true }

# Cumulus dependencies
cumulus-pallet-aura-ext = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-pallet-xcm = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-primitives-aura = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-primitives-parachain-inherent = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
staging-parachain-info = { workspace = true }
parachains-common = { workspace = true }

# Polkadot dependencies
polkadot-parachain = { workspace = true }
xcm-builder = { workspace = true }
pallet-xcm = { workspace = true }
xcm-executor = { workspace = true }
polkadot-xcm = { workspace = true }
polkadot-runtime-common = { workspace = true }
xcm-runtime-apis = { workspace = true }

# Substrate dependencies
primitive-types = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-executive = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }
frame-try-runtime = { workspace = true, optional = true }
pallet-aura = { workspace = true }
pallet-balances = { workspace = true }
pallet-collective = { workspace = true }
pallet-conviction-voting = { workspace = true }
pallet-preimage = { workspace = true }
pallet-session = { workspace = true }
pallet-proxy = { workspace = true }
pallet-multisig = { workspace = true }
pallet-referenda = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-uniques = { workspace = true }
pallet-utility = { workspace = true }
pallet-whitelist = { workspace = true }
pallet-message-queue = { workspace = true }

sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-externalities = { workspace = true }
sp-genesis-builder = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-staking = { workspace = true }
sp-trie = { workspace = true }
sp-io = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-nft/runtime-benchmarks",
    "pallet-marketplace/runtime-benchmarks",
    "pallet-xyk/runtime-benchmarks",
    "pallet-lbp/runtime-benchmarks",
    "pallet-staking/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-collator-selection/runtime-benchmarks",
    "pallet-xcm/runtime-benchmarks",
    "xcm-builder/runtime-benchmarks",
    "pallet-asset-registry/runtime-benchmarks",
    "pallet-duster/runtime-benchmarks",
    "pallet-democracy/runtime-benchmarks",
    "pallet-treasury/runtime-benchmarks",
    "pallet-scheduler/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-tips/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-preimage/runtime-benchmarks",
    "pallet-xyk-liquidity-mining-benchmarking/runtime-benchmarks",
    "pallet-uniques/runtime-benchmarks",
    "orml-benchmarking",
    "pallet-transaction-pause/runtime-benchmarks",
    "pallet-ema-oracle/runtime-benchmarks",
    "cumulus-pallet-xcmp-queue/runtime-benchmarks",
    "cumulus-pallet-parachain-system/runtime-benchmarks",
    "pallet-elections-phragmen/runtime-benchmarks",
    "pallet-state-trie-migration/runtime-benchmarks",
    "pallet-conviction-voting/runtime-benchmarks",
    "pallet-referenda/runtime-benchmarks",
    "pallet-whitelist/runtime-benchmarks",
    "pallet-message-queue/runtime-benchmarks",
    "cumulus-pallet-parachain-system/runtime-benchmarks",
]
std = [
    "codec/std",
    "serde",
    "scale-info/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "frame-try-runtime/std",
    "frame-benchmarking/std",
    "pallet-currencies/std",
    "orml-tokens/std",
    "orml-traits/std",
    "orml-vesting/std",
    "orml-xtokens/std",
    "orml-xcm-support/std",
    "orml-xcm/std",
    "orml-unknown-tokens/std",
    "orml-benchmarking/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-pallet-aura-ext/std",
    "cumulus-pallet-xcm/std",
    "cumulus-pallet-xcmp-queue/std",
    "cumulus-primitives-aura/std",
    "cumulus-primitives-core/std",
    "polkadot-xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "xcm-runtime-apis/std",
    "pallet-xcm/std",
    "staging-parachain-info/std",
    "pallet-xyk/std",
    "pallet-duster/std",
    "pallet-asset-registry/std",
    "pallet-aura/std",
    "pallet-balances/std",
    "pallet-elections-phragmen/std",
    "pallet-nft/std",
    "pallet-marketplace/std",
    "pallet-session/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-pause/std",
    "pallet-transaction-multi-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-lbp/std",
    "pallet-utility/std",
    "pallet-xyk-liquidity-mining/std",
    "pallet-broadcast/std",
    "pallet-staking/std",
    "hydradx-traits/std",
    "hydradx-adapters/std",
    "sp-api/std",
    "sp-arithmetic/std",
    "sp-block-builder/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-genesis-builder/std",
    "sp-io/std",
    "sp-inherents/std",
    "sp-externalities/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-trie/std",
    "sp-transaction-pool/std",
    "sp-version/std",
    "pallet-treasury/std",
    "pallet-collective/std",
    "pallet-democracy/std",
    "pallet-proxy/std",
    "pallet-multisig/std",
    "pallet-scheduler/std",
    "pallet-tips/std",
    "pallet-collator-selection/std",
    "pallet-authorship/std",
    "pallet-uniques/std",
    "pallet-preimage/std",
    "pallet-identity/std",
    "pallet-ema-oracle/std",
    "pallet-message-queue/std",
    "pallet-state-trie-migration/std",
    "pallet-conviction-voting/std",
    "pallet-referenda/std",
    "pallet-whitelist/std",
    "cumulus-primitives-utility/std",
    "parachains-common/std",
    "polkadot-runtime-common/std",
]
try-runtime= [
    "frame-try-runtime",
    "frame-executive/try-runtime",
    "frame-system/try-runtime",
    "pallet-currencies/try-runtime",
    "orml-tokens/try-runtime",
    "orml-vesting/try-runtime",
    "orml-xtokens/try-runtime",
    "orml-xcm/try-runtime",
    "orml-unknown-tokens/try-runtime",
    "cumulus-pallet-parachain-system/try-runtime",
    "cumulus-pallet-aura-ext/try-runtime",
    "cumulus-pallet-xcm/try-runtime",
    "cumulus-pallet-xcmp-queue/try-runtime",
    "staging-parachain-info/try-runtime",
    "pallet-aura/try-runtime",
    "pallet-balances/try-runtime",
    "pallet-elections-phragmen/try-runtime",
    "pallet-session/try-runtime",
    "pallet-timestamp/try-runtime",
    "pallet-transaction-payment/try-runtime",
    "pallet-transaction-pause/try-runtime",
    "pallet-utility/try-runtime",
    "pallet-treasury/try-runtime",
    "pallet-collective/try-runtime",
    "pallet-democracy/try-runtime",
    "pallet-proxy/try-runtime",
    "pallet-multisig/try-runtime",
    "pallet-scheduler/try-runtime",
    "pallet-tips/try-runtime",
    "pallet-collator-selection/try-runtime",
    "pallet-authorship/try-runtime",
    "pallet-uniques/try-runtime",
    "pallet-preimage/try-runtime",
    "pallet-identity/try-runtime",
    "pallet-xcm/try-runtime",
    "pallet-asset-registry/try-runtime",
    "pallet-xyk/try-runtime",
    "pallet-duster/try-runtime",
    "pallet-lbp/try-runtime",
    "pallet-nft/try-runtime",
    "pallet-transaction-multi-payment/try-runtime",
    "pallet-relaychain-info/try-runtime",
    "pallet-marketplace/try-runtime",
    "pallet-route-executor/try-runtime",
    "pallet-xyk-liquidity-mining/try-runtime",
    "warehouse-liquidity-mining/try-runtime",
    "pallet-ema-oracle/try-runtime",
    "pallet-collator-rewards/try-runtime",
    "pallet-state-trie-migration/try-runtime",
    "pallet-message-queue/try-runtime",
    "pallet-conviction-voting/try-runtime",
    "pallet-referenda/try-runtime",
    "pallet-whitelist/try-runtime",
    "pallet-broadcast/try-runtime",
    "pallet-staking/try-runtime",
]
