[patch.crates-io]
frame-support = {default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-rc5', version = '2.0.0-rc5'}
frame-system = {default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-rc5', version = '2.0.0-rc5'}
sp-core = {default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-rc5', version = '2.0.0-rc5'}
sp-io = {default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-rc5', version = '2.0.0-rc5'}
sp-runtime = {default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-rc5', version = '2.0.0-rc5'}
sp-std = {default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-rc5', version = '2.0.0-rc5'}


[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/amm',
    'pallets/asset-registry',
    'pallets/template',
    'primitives',
    'runtime',
]
