[patch.crates-io]
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
frame-executive = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
frame-support = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
frame-system = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
frame-system-benchmarking = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-authorship = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-aura = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-balances = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-session = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-sudo = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-cli = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-client-api = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-client-db = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-consensus = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-consensus-epochs = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-executor = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-informant = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-keystore = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-network = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-offchain = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-rpc = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-service = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-application-crypto = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-arithmetic = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-consensus = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-externalities = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-inherents = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-io = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-offchain = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-rpc = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-runtime-interface = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-session = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-staking = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-storage = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-state-machine = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-tracing = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-trie = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
sp-version = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }

pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }

# ORML dependencies
orml-currencies = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master' }
orml-tokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master' }
orml-traits = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master' }

[patch."https://github.com/paritytech/cumulus"]
sp-externalities = { git = 'https://github.com/paritytech/substrate', rev = '5c70d7bb2b78d4ed5e3aa4fd0449cc6c81d3db98' }
# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-service = { git = "https://github.com/paritytech/polkadot", rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-runtime-common = { git = 'https://github.com/paritytech/polkadot', rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-test-runtime = { git = 'https://github.com/paritytech/polkadot', rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }
polkadot-test-client = { git = 'https://github.com/paritytech/polkadot', rev = '184a4b1a05a6cc2c64547f3811af1be2ab8f70b2' }

[profile.release]
panic = 'unwind'

[workspace]
members = [
  # 'pallets/proposal', Update this
  'node',
  'pallets/amm',
  'pallets/asset-registry',
  'pallets/exchange',
  'pallets/transaction-multi-payment',
  'primitives',
  'runtime',
]
