[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'runtime/common',
  'runtime/basilisk',
  'runtime/testing-basilisk',
  'pallets/marketplace',
  'pallets/duster',
  'pallets/xyk',
  'integration-tests',
  'integration-tests/parachain-runtime-mock'
]

[patch."https://github.com/paritytech/substrate"]
frame-benchmarking = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-benchmarking-cli = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-election-provider-support = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-executive = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-support = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-support-procedural = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-support-procedural-tools = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-support-procedural-tools-derive = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-system = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-system-benchmarking = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-system-rpc-runtime-api = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
frame-try-runtime = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-aura = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-authority-discovery = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-authorship = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-babe = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-balances = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-bounties = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-collective = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-democracy = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-election-provider-multi-phase = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-elections-phragmen = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-gilt = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-grandpa = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-identity = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-im-online = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-indices = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-membership = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-multisig = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-offences = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-offences-benchmarking = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-proxy = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-recovery = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-scheduler = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-session = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-session-benchmarking = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-society = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-staking = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-staking-reward-curve = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-staking-reward-fn = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-sudo = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-timestamp = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-tips = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-transaction-payment = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-transaction-payment-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-treasury = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-uniques = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-utility = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-vesting = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
remote-externalities = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-authority-discovery = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-basic-authorship = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-block-builder = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-chain-spec = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-cli = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-client-api = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-client-db = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-consensus = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-consensus-aura = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-consensus-babe = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-consensus-babe-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-consensus-epochs = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-consensus-slots = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-executor = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-executor-common = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-executor-wasmtime = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-finality-grandpa = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-finality-grandpa-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-informant = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-keystore = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-network = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-network-common = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-network-gossip = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-offchain = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-rpc-api = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-rpc-server = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-service = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-sync-state-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-telemetry = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-tracing = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-transaction-pool = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-transaction-pool-api = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sc-utils = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-api = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-application-crypto = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-arithmetic = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-authority-discovery = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-authorship = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-block-builder = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-blockchain = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-consensus = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-consensus-aura = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-consensus-babe = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-consensus-slots = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-consensus-vrf = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-core = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-debug-derive = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-externalities = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-finality-grandpa = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-inherents = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-io = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-keyring = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-keystore = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-maybe-compressed-blob = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-npos-elections = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-offchain = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-runtime = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-runtime-interface = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-runtime-interface-proc-macro = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-session = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-staking = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-state-machine = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-std = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-storage = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-timestamp = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-tracing = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-transaction-pool = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-trie = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-version = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-wasm-interface = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
substrate-build-script-utils = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
substrate-frame-rpc-system = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
substrate-prometheus-endpoint = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
substrate-wasm-builder = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
try-runtime-cli = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-mmr = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
pallet-mmr-rpc = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }
sp-mmr-primitives = { git = "https://github.com/galacticcouncil//substrate", branch = "dont-wipe-authorities" }

[patch."https://github.com/paritytech/polkadot"]
kusama-runtime = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
pallet-xcm = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-cli = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-client = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-core-primitives = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-node-core-pvf = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-node-network-protocol = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-node-primitives = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-node-subsystem = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-overseer = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-parachain = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-primitives = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-runtime = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-runtime-common = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-runtime-parachains = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-service = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
polkadot-statement-table = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
rococo-runtime = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
westend-runtime = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
xcm = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
xcm-builder = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }
xcm-executor = { git = "https://github.com/galacticcouncil/polkadot", branch = "fix-xcm-executor-atomicity-9-29-1" }

[patch."https://github.com/paritytech/cumulus"]
pallet-collator-selection = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-client-cli = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-client-consensus-aura = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-client-consensus-common = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-client-consensus-relay-chain = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-client-network = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-client-service = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-primitives-core = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-primitives-utility = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
parachain-info = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
cumulus-relay-chain-interface = { git = "https://github.com/paritytech//cumulus", branch = "polkadot-v0.9.29" }
