[patch.crates-io]
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
frame-executive = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
frame-support = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
frame-system-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-authorship = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-aura = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-collective = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-session = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-society = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-sudo = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-vesting = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-cli = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-client-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-client-db = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-consensus = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-consensus-epochs = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-executor = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-informant = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-keystore = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-network = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-offchain = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-rpc = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-service = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sc-tracing = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-application-crypto = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-arithmetic = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-consensus = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-externalities = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-inherents = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-offchain = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-rpc = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-runtime-interface = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-session = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-std = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-staking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-storage = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-state-machine = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-timestamp = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-tracing = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-trie = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
sp-version = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
substrate-test-client = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
substrate-test-runtime-client = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.3" }

sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }



# ORML dependencies
orml-currencies = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }
orml-tokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }
#orml-unknown-tokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }
orml-traits = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }
orml-utilities = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }
#orml-xtokens= { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }
#orml-xcm-support = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '6862e1ced561c1c970afc8c5d00d2e023fc3b965' }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.3" }
polkadot-runtime-common = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.3" }
polkadot-test-runtime = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.3" }
polkadot-test-client = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.3" }
#xcm = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.3" }
#xcm-builder = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.3" }
#6862e1ced561c1c970afc8c5d00d2e023fc3b965xcm-executor = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.3" }

hydra-dx-build-script-utils = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
primitives = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-xyk = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-transaction-multi-payment = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-multi-payment-benchmarking = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-exchange = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-exchange-benchmarking = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-asset-registry = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-xyk-rpc-runtime-api = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }
pallet-xyk-rpc = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }

[profile.release]
panic = 'unwind'

[workspace]
members = [
  # 'pallets/proposal', Update this
  'node',
  'runtime',
]
