[profile.release]
panic = 'unwind'

[workspace]
members = [
  # 'pallets/proposal', Update this
  'node',
  'pallets/amm',
  'pallets/asset-registry',
  'pallets/exchange',
  'pallets/template',
  'primitives',
  'runtime',
]
