[package]
authors = ['GalacticCouncil']
description = 'HydraDX Exchange Module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hack.hydradx-node'
license = 'Unlicense'
name = 'pallet-faucet'
repository = 'https://github.com/galacticcouncil/hack.hydradx-node'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
primitive-types = {default-features = false, version = '0.7.2'}
serde = {features = ['derive'], optional = true, version = '1.0.101'}
codec = {package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Local dependencies
primitives = {path = '../../primitives', default-features = false, version = '3.0.0'}

# ORML dependencies
orml-tokens = {default-features = false, version = "0.4.0-dev"}
orml-traits = {default-features = false, version = "0.4.0-dev"}

# Substrate dependencies
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}

sp-core = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}

[dev-dependencies]
sp-io = {default-features = false, version = '3.0.0'}

[features]
default = ['std']
std = [
  'serde/std',
  'codec/std',
  'sp-std/std',
  'frame-support/std',
  'frame-system/std',
]
