[package]
name = 'pallet-transaction-multi-payment'
authors = ['GalacticCoucil']
description = 'Transaction multi currency payment support module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydra-dx'
license = 'Unlicense'
repository = 'https://github.com/galacticcouncil/hydra-dx'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
primitive-types = {default-features = false, version = '0.7.2'}
serde = {features = ['derive'], optional = true, version = '1.0.101'}
codec = {package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Local dependecies
primitives = {path = '../../primitives', default-features = false, version = '3.0.0'}

# ORML dependencies
orml-tokens = {default-features = false, version = "0.4.0-dev"}
orml-traits = {default-features = false, version = "0.4.0-dev"}

# Substrate dependencies
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}
pallet-transaction-payment = {default-features = false, version = '3.0.0'}

sp-core = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}
sp-api= {default-features = false, version = '3.0.0'}
pallet-balances = {default-features = false, version = '3.0.0' }
pallet-asset-registry = {path = '../asset-registry', default-features = false, version = '3.0.0'}
pallet-amm = {path = '../amm', default-features = false, version = '3.0.0'}

[dev-dependencies]
sp-io = {default-features = false, version = '3.0.0'}
pallet-transaction-payment = {default-features = false, version = '3.0.0' }
orml-currencies = {default-features = false, version = "0.4.0-dev"}

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'sp-core/std',
    'sp-api/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'orml-tokens/std',
    'orml-traits/std',
    'pallet-balances/std',
    'pallet-asset-registry/std',
    'pallet-amm/std',
]

