name: smoke-test
on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  test-inclusion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/download-artifact@v2
        name: Download basilisk binary
        with:
          name: basilisk
          path: target/release/basilisk
      - uses: robinraju/release-downloader@v1
        name: Download relay chain binary
        with:
          repository: paritytech/polkadot
          tag: v0.9.1
          fileName: polkadot
          out-file-path: ../polkadot/target/release
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: '14'
      - run: ./install_polkadot_launch.sh
        name: Setup polkadot launch
        working-directory: scripts
      - run: polkadot-launch config.json
        name: Launch rococo local
        working-directory: rococo-local
      - run: npm start 1000
        name: Wait for parachain inclusion
        working-directory: scripts/wait-for-inclusion
