name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2020-06-04
        target: wasm32-unknown-unknown
        default: true
    - name: Cache Rust dependencies
      uses: actions/cache@v1.1.2
      with:
        path: target
        key: build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          build-
    - run: ./scripts/init.sh
    - run: time cargo test --all --release --verbose --locked 
    - run: time cargo build --release --verbose
