name: build-and-deploy
on:
  push:
    branches:
      - testnet-automation
  workflow_dispatch:
  pull_request:

jobs:
  run-external-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_DEPLOYMENT_TOKEN }}
          repository: galacticcouncil/testnet-deployment
          event-type: run-k8s-deployment
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
