name: build-and-deploy
on:
  push:
    branches:
      - testnet-automation
  workflow_dispatch:
  pull_request:

jobs:
  
  build-and-publish-docker-image:
    needs: pop-runner-instance
    runs-on: ${{ needs.pop-runner-instance.outputs.runner }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      ECR_URL: 601305236792.dkr.ecr.eu-west-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Configure AWS CLI
        run: |
          sudo apt-get -y update
          sudo apt-get -y install awscli
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}; aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}; aws configure set default.region eu-west-1    
      - uses: actions/download-artifact@v2
        name: Download basilisk binary
        with:
          name: basilisk
          path: .
      - name: Add execution for basilisk
        run: chmod +x basilisk
      - name: Sleep for 60 seconds
        run: sleep 60
      - name: install docker
        run: sudo snap install docker
      - name: Sleep for 30 seconds
        run: sleep 30s
      - name: build docker image
        run: sudo docker build -t basilisk:latest .
      - name: get ecr credentials
        run: aws ecr get-login-password --region eu-west-1 | sudo docker login --username AWS --password-stdin ${{ env.ECR_URL }}
      - name: push image to ecr repository
        run: sudo docker tag basilisk:latest ${{ env.ECR_URL }}/basilisk
      - run: sudo docker push ${{ env.ECR_URL }}/basilisk:latest
